name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove rust-toolchain.toml
        run: rm rust-toolchain.toml
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1
        with:
          default: true
          ldproxy: true
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
